name: calculator
description: "A new calculator Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  math_expressions:
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/calculator.png
  
  fonts:
    - family: Chillax
      fonts:
        - asset: Assets/Chillax-TTF/Chillax-Regular.ttf
          weight: 400
        - asset: Assets/Chillax-TTF/Chillax-Light.ttf
          weight: 300
        - asset: Assets/Chillax-TTF/Chillax-Medium.ttf
          weight: 500
        - asset: Assets/Chillax-TTF/Chillax-Semibold.ttf
          weight: 600
        - asset: Assets/Chillax-TTF/Chillax-Bold.ttf
          weight: 700
        - asset: Assets/Chillax-TTF/Chillax-Extralight.ttf
          weight: 200

  
flutter_icons:
  android: true
  ios: true
  image_path: "Assets/calculator.png"
